### ISSUE TITLE
Hello, I downloaded your Kaggle data and encountered an error using test.py.

### ISSUE THREAD

**Issue by Lz-Sadada** [Johnathan-Xie/ZSD-YOLO#6]
Fusing layers... 
torch.Size([17, 512])
Model Summary: 226 layers, 8432590 parameters, 0 gradients, 20.7 GFLOPS
<class 'utils.datasets.LoadImagesAndLabels'>
val: Scanning 'data\coco\labels2014_zsd_self_test_l_48_17\val2014' images and labels... 0 found, 2729 missing, 0 empty, 0 corrupted: 100%|██████████| 2729/2729 [00:00<00:00, 8621.79it/s]
val: WARNING: No labels found in data\coco\labels2014_zsd_self_test_l_48_17\val2014.cache. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
val: New cache created: data\coco\labels2014_zsd_self_test_l_48_17\val2014.cache
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 86/86 [00:19<00:00,  4.40it/s]
NO STATS
Traceback (most recent call last):
  File "E:\pycharm-community-2022.3.2\PyCharm-Community-Edition-2022.3.2\code\ZSD-YOLO-main\test.py", line 494, in <module>
    test(opt.data,
  File "E:\Anaconda3-2022.10\envs\ZSD-YOLO\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "E:\pycharm-community-2022.3.2\PyCharm-Community-Edition-2022.3.2\code\ZSD-YOLO-main\test.py", line 382, in test
    recall_info = process_recall(zsd_recall_correct, zsd_recall_classes, nt)
  File "E:\pycharm-community-2022.3.2\PyCharm-Community-Edition-2022.3.2\code\ZSD-YOLO-main\test.py", line 51, in process_recall
    zsd_recall_correct, zsd_recall_classes = torch.stack(zsd_recall_correct), torch.Tensor(zsd_recall_classes).type(torch.LongTensor)
RuntimeError: stack expects a non-empty TensorList

**Comment by Johnathan-Xie** [comment]
Could you share the information on your conda environment? It is possible the packages are not matching because this work was originally done over a year ago.
